tag : "MDXFinal"
dataset_dir : "/dataset/"
save_dir : "/saves/"
batch_size : 8
lr : 1e-3
random_hop : True
num_workers : 12
max_epochs : 150
min_epochs : 10

stft : 
  nfft : 512
  hop_size : 256
  freeze_parameters : True
  padding : True
  pad_mode : "reflect"
  scaled : False

ema : 
  beta : 0.999
  step_start : 2000

models :
  basic : 
    in_channels : 2
    out_channels : 2
    channels : [48, 96, 144, 192, 240, 288]
    attention_channels : [False, False, False, False, True]
    min_output_height : 257
    min_output_width : 150
    depth : 4
    kernel_size : 3
    padding : 1
    stride : 2
    dilation : 1
    gn_channels : 8
    dropout : 0.1
    Masking : True
  fou :
    in_channels : 2
    out_channels : 2
    channels : [48, 96, 144, 192, 240, 288]
    depth : 4
    attention_channels : [False, False, False, False, True]
    width : 256
    gn_channels : 8
    dropout : 0.1

prep :
  sr : 44100
  cons_zeros : 200000