tag : "FouivreTesting"
dataset_dir : "/dataset/"
save_dir : "/saves/"
batch_size : 2
lr : 1e-3
random_hop : True
num_workers : 12
max_epochs : 150
min_epochs : 10

stft : 
  nfft : 512
  hop_size : 128
  freeze_parameters : True
  padding : True
  pad_mode : "reflect"
  scaled : False

ema : 
  beta : 0.999
  step_start : 2000

models :
  basic : 
    in_channels : 2
    out_channels : 2
    channels : [64, 128, 192, 256, 320, 384]
    attention_channels : [False, False, False, False, True]
    min_output_height : 257
    min_output_width : 150
    depth : 3
    kernel_size : 3
    padding : 1
    stride : 2
    dilation : 1
    gn_channels : 8
    dropout : 0.1
    Masking : True
  basic2 : 
    channels : 256
    kernel_size : 3
    levels : 12
    depth : 3
    chgn : 8 
    dropout : 0.2
    io : 257
  basic3 : 
    channels : 64
    depth : 5
    kernel_size : 9
    stride : 4
    resu_channels : [128, 256]
    chgn : 8 
    dropout : 0.2
    io : 257
  fou :
    in_channels : 2
    out_channels : 2
    channels : [64, 128, 192, 256, 320, 384]
    depth : 2
    attention_channels : [False, False, False, False, True]
    width : 256
    gn_channels : 8
    dropout : 0.1
  fou2 :
    channel : 64
    level : 12
    depth : 2
    width : 256
    gn_channels : 8
    dropout : 0.2
  fouivre : 
    freq : 257
    channels : [64, 128, 192, 256, 320]
    depth : 2
    chgn : 8
    dropout : 0.1
    kernel_size : 3
    stride : 2
    n_heads : 8
    bottle_depth : 3
  foumou : 
    freq : 257
    channels : [64, 128, 192, 256, 320]
    attention_channels : [False, False, False, False, True]
    depth : 2
    chgn : 8
    dropout : 0.1
    kernel_size : 3
    stride : 2
    n_heads : 8

prep :
  sr : 44100
  cons_zeros : 200000